    <div class="list-group">
        <a href="$context$admin/clientview" class="list-group-item $client$">
            <span class="glyphicon  glyphicon-user"></span> Client <span class="badge">$clients$</span>
        </a>
        <a href="$context$admin/vendorview" class="list-group-item $vendor$">
            <span class="glyphicon  glyphicon-user"></span> Vendors <span class="badge">$vendors$</span>
        </a>
        <a href="$context$admin/reports" class="list-group-item $reports$">
            <span class="glyphicon glyphicon-music"></span> Reports <span class="badge">2</span>
        </a>
        <a href="$context$admin/sms" class="list-group-item $sms$">
            <span class="glyphicon glyphicon-envelope"></span> SMS <span class="badge">3</span>
        </a>
        <a href="$context$admin/adminutils" class="list-group-item $admintuils$">
            <span class="glyphicon glyphicon-envelope"></span> Utils <span class="badge">1</span>
        </a>
    </div>

<!--sidebar-box-->