    <div class="list-group">
        <a href="$context$client/vendorview" class="list-group-item $client$">
            <span class="glyphicon  glyphicon-user"></span> Vendors <span class="badge">$vendors$</span>
        </a>
       
        <a href="$context$client/clientvendorreports" class="list-group-item $reports$">
            <span class="glyphicon glyphicon-music"></span> Reports <span class="badge">2</span>
        </a>
        <a href="$context$client/clientutils" class="list-group-item $vendorutils$">
            <span class="glyphicon glyphicon-envelope"></span> Utils <span class="badge">3</span>
        </a>
    </div>

<!--sidebar-box-->