<footer id="footer">
	<div class="container">

		<div class="row">
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>MENU</h3>
					<ul class="footer_list ">
						<li id="menu-item-1549"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1549"><a
									href="http://www.facilitechintl.com/about/">About
										FaciliTech</a></li>
								<li id="menu-item-1554"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1554"><a
									href="http://www.facilitechintl.com/gold-standard/">Gold
										Standard</a></li>
								<li id="menu-item-1247"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1247"><a
									href="http://www.facilitechintl.com/boots-on-the-ground/">Boots
										on the Ground</a></li>
								<li id="menu-item-1393"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1393"><a
									href="http://www.facilitechintl.com/case-studies/">Case
										Studies</a></li>
								<li id="menu-item-1248"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1248"><a
									href="http://www.facilitechintl.com/additional-services/">Additional
										Services</a></li>
								<li id="menu-item-1250"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1250"><a
									href="http://www.facilitechintl.com/webinars/">Webinars</a></li>
								<li id="menu-item-1249"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1249"><a
									href="http://www.facilitechintl.com/blog/">Blog</a></li>
								<li id="menu-item-1251"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1251"><a
									href="http://www.facilitechintl.com/contact-us/">Contact</a></li>
								<li id="menu-item-1550"
									class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1550"><a
									href="http://www.facilitechintl.com/join-the-team/">Join
										the Team</a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>OUR PROMISE</h3>
					<P>MISSION:: To provide unparalleled customer service,
								stability, attention to detail and accountability to all our
								clients, contractors, and employees. To bless those around us
								and live a high quality of life.</P>

							<P>VISION:: To build a global consolidated facility
								management firm built on a solid ROCK as a foundation and have
								the highest level of customer retention possible.</P>

							<P>VALUES:: God, Family, then Business.</P>
				</div>
			</div>
			<!--footer col-->
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>CONTACT INFO</h3>

					<ul class="contact footer_list">
						<li><p class="text_9">
								<strong><i class="fa fa-map-marker"></i> Address:</strong> 19410 Highway 99 Lynnwood, WA 98036
							</p></li>
						
						<li>
							<p class="text_9">
								<strong><i class="fa fa-phone"></i> Phone:</strong> 1-855-767-7768
							</p>
						</li>
						
					</ul>
				</div>
			</div>
			<!--footer col-->
		</div>
	</div>
</footer>

