<div class="navbar navbar-default navbar-static-top yamm sticky"
	role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="pull-left" href="index.xhtml"> 
	  				<img class="img-responsive"  style="max-width:300px;" 
	  				src="$context$images/480x90-gold.png" alt="">
	  				</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="$index$"><a href="index.xhtml">HOME</a></li> 
				<li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">COMPANY <i class="fa fa-angle-down"></i></a>
                          <ul class="dropdown-menu" role="menu">
                          <li id="menu-item-1548"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1548"><a
								href="http://www.facilitechintl.com/about/">About FaciliTech</a></li>
							<li id="menu-item-1555"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1555"><a
								href="http://www.facilitechintl.com/gold-standard/">Gold
									Standard</a></li>
							<li id="menu-item-1164"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1164"><a
								href="http://www.facilitechintl.com/boots-on-the-ground/">Boots
									on the Ground</a></li>
							<li id="menu-item-1357"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1357"><a
								href="http://www.facilitechintl.com/case-studies/">Case
									Studies</a></li>
							<li id="menu-item-1165"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1165"><a
								href="http://www.facilitechintl.com/additional-services/">Additional
									Services</a></li>
							<li id="menu-item-1267"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1267"><a
								href="http://www.facilitechintl.com/webinars/">Webinars</a></li>
                 </ul>
                </li>
                <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">SERVICES <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                  <li id="menu-item-1173"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1173"><a
								href="http://www.facilitechintl.com/asphalt-services/">Asphalt</a></li>
							<li id="menu-item-1389"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1389"><a
								href="http://www.facilitechintl.com/electrical-services/">Electrical
									and Lighting</a></li>
							<li id="menu-item-1168"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1168"><a
								href="http://www.facilitechintl.com/janitorial-services/">Janitorial</a></li>
							<li id="menu-item-1170"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1170"><a
								href="http://www.facilitechintl.com/handyman-services/">Handyman</a></li>
							<li id="menu-item-1169"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1169"><a
								href="http://www.facilitechintl.com/hvac-services/">HVAC</a></li>
							<li id="menu-item-1171"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1171"><a
								href="http://www.facilitechintl.com/landscaping-services/">Landscaping</a></li>
							<li id="menu-item-1174"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1174"><a
								href="http://www.facilitechintl.com/lot-sweeping/">Lot
									Sweeping</a></li>
							<li id="menu-item-1388"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1388"><a
								href="http://www.facilitechintl.com/painting-services/">Painting</a></li>
							<li id="menu-item-1387"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1387"><a
								href="http://www.facilitechintl.com/plumbing-services/">Plumbing</a></li>
							<li id="menu-item-1172"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1172"><a
								href="http://www.facilitechintl.com/risk-management-services/">Risk
									Management</a></li>
							<li id="menu-item-1166"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1166"><a
								href="http://www.facilitechintl.com/skilled-trade-services/">Skilled
									Trade</a></li>
							<li id="menu-item-1167"
								class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1167"><a
								href="http://www.facilitechintl.com/snow-and-ice/">Snow and
									Ice</a></li>
                            </ul>
                        </li>
                
				
				<!-- log in menu starts -->
				<li class="dropdown"><a href="#" class=" dropdown-toggle"
					data-toggle="dropdown"><i class="fa fa-lock"></i></a>
					<div
						class="dropdown-menu dropdown-menu-right dropdown-login-box animated fadeInUp">
						<form role="form" action="login" method="post">
							<h4>Signin</h4>

							<div class="form-group">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user"></i></span>
									<input type="text" name="userId" class="form-control" placeholder="Username">
								</div>
								<br>
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock"></i></span>
									<input type="password" name="password" class="form-control"
										placeholder="Password">
								</div>
								<div class="checkbox pull-left">
									<label> <input type="checkbox"> Remember me
									</label>
								</div>
								<button type="submit" class="btn btn-theme-bg pull-right">Login</button>
								<div class="clearfix"></div>
								<hr>
								
							</div>
						</form>
					</div></li>
				<!-- log in menu ends -->
				
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
	<!--container-->
</div>

