    <div class="list-group">
        <a href="$context$vendor/clientview" class="list-group-item $client$">
            <span class="glyphicon  glyphicon-user"></span> Client <span class="badge">$clients$</span>
        </a>
       
        <a href="$context$vendor/vendorclientreports" class="list-group-item $reports$">
            <span class="glyphicon glyphicon-music"></span> Reports <span class="badge">2</span>
        </a>
        <a href="$context$vendor/vendorutils" class="list-group-item $vendorutils$">
            <span class="glyphicon glyphicon-envelope"></span> Utils <span class="badge">3</span>
        </a>
    </div>

<!--sidebar-box-->